package com.quizcomm.util;

public interface Constants {
	
	 String QUIZ_STATUS_COMPLETE = "COMPLETE"; 
	 String QUIZ_STATUS_INCOMPLETE = "INCOMPLETE"; 
	 String QUIZ_STATUS_PROMOTED = "PROMOTED";
	 String QUIZ_STATUS_COMPLETE_SUCCESS = "SUCCESS"; 
	 String QUIZ_STATUS_COMPLETE_FAILURE = "FAILURE";
	 String QUESTION_TYPE_MULTI = "MULTI";
	 String QUESTION_TYPE_SINGLE = "SINGLE";
	 String QUIZ_CANCEL_SUCCESS = "SUCCESS";
	 String QUIZ_CANCEL_PROMOTED = "FAILURE";
	 String QUIZ_CANCEL_FAILURE = "FAILURE";

}
